### ISSUE TITLE
I want to consult some questions

### ISSUE THREAD

**Issue by XiaoBingCQY** [Dezreal/VideoActionClassifier#1]
First of all, thank you for your contributions.
I think it's not very good to recognize every frame,after all,action is a continuous event.Can we do any modification?
If it is convenient for you, could you please give me your contact informatio？Thank you very much.

**Comment by Dezreal** [comment]
Thanks for your attention and your issue about continuous frames. The method I used is to calculate 8 frames at even intervals in time sequence for each video. In fact, this model is migrated from [ST-GCN]( https://github.com/yysijie/st-gcn). This project is currently only at the application level, and model improvement or innovation is the future work.

感谢关注，对于你提出的连续帧问题，目前我用的是方法是对每个视频片段按时间顺序取了间隔均匀的8帧进行计算，事实上所用到的模型迁移自[ST-GCN](https://github.com/yysijie/st-gcn)，这个项目现在仅停留在应用层面，模型的改进或创新是以后的工作了。

**Comment by XiaoBingCQY** [comment]
非常感谢您的回复，浪费了您的宝贵时间。
如果我想等一个视频播放完，也就是说输入一个完整的动作序列然后再进行识别，您觉得可行吗？如果可行的话该怎么做？
如果方便的话，您可以加我的微信：13914679431，我想向你咨询一些问题。
